{"rqResponse": {
   "rqAuthentication": "Session:MITSE|bzZahzidQbAnNala2225",
   "dsMovie": {"ttMovie":    [
            {
         "dMovieObj": 36,
         "cMovieCode": "INTHE001",
         "cMovieTitle": "In the House",
         "iMovieYear": 2013,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 105,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55490
      },
            {
         "dMovieObj": 145,
         "cMovieCode": "INHER001",
         "cMovieTitle": "Inherit The Wind",
         "iMovieYear": 1960,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 128,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55520
      },
            {
         "dMovieObj": 239,
         "cMovieCode": "MANON001",
         "cMovieTitle": "Manon of the Spring",
         "iMovieYear": 1986,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 120,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55775
      },
            {
         "dMovieObj": 275,
         "cMovieCode": "ANIGH001",
         "cMovieTitle": "A Night at the Opera",
         "iMovieYear": 1935,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 96,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54615
      },
            {
         "dMovieObj": 277,
         "cMovieCode": "BEING001",
         "cMovieTitle": "Being There",
         "iMovieYear": 1979,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 130,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54810
      },
            {
         "dMovieObj": 290,
         "cMovieCode": "ORPHA001",
         "cMovieTitle": "Orphans of the Storm",
         "iMovieYear": 1921,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 150,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 56015
      },
            {
         "dMovieObj": 546,
         "cMovieCode": "ACEIN001",
         "cMovieTitle": "Ace in the Hole",
         "iMovieYear": 1951,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 111,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54655
      },
            {
         "dMovieObj": 650,
         "cMovieCode": "INTHE002",
         "cMovieTitle": "In the Loop",
         "iMovieYear": 2009,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 106,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55495
      },
            {
         "dMovieObj": 696,
         "cMovieCode": "GONEW001",
         "cMovieTitle": "Gone with the Wind",
         "iMovieYear": 1939,
         "iAgeRestriction": 10,
         "cAgeReason": "LN",
         "iRuntime": 238,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 55325
      },
            {
         "dMovieObj": 791,
         "cMovieCode": "MANOS001",
         "cMovieTitle": "Manos: The Hands of Fate",
         "iMovieYear": 1966,
         "iAgeRestriction": 10,
         "cAgeReason": "NS",
         "iRuntime": 74,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 0
      },
            {
         "dMovieObj": 793,
         "cMovieCode": "METAL001",
         "cMovieTitle": "Metallica: Through the Never",
         "iMovieYear": 2013,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 93,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 57474
      },
            {
         "dMovieObj": 866,
         "cMovieCode": "FLESH001",
         "cMovieTitle": "Flesh and the Devil",
         "iMovieYear": 1926,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 109,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55235
      },
            {
         "dMovieObj": 877,
         "cMovieCode": "ONTHE001",
         "cMovieTitle": "On the Waterfront",
         "iMovieYear": 1954,
         "iAgeRestriction": 13,
         "cAgeReason": "NR",
         "iRuntime": 108,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55995
      },
            {
         "dMovieObj": 880,
         "cMovieCode": "RAISE001",
         "cMovieTitle": "Raise the Red Lantern",
         "iMovieYear": 1991,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 125,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 56135
      },
            {
         "dMovieObj": 942,
         "cMovieCode": "FIRES001",
         "cMovieTitle": "Fires on the Plain",
         "iMovieYear": 1959,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 108,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55220
      },
            {
         "dMovieObj": 1028,
         "cMovieCode": "INTOT001",
         "cMovieTitle": "Into the Wild",
         "iMovieYear": 2007,
         "iAgeRestriction": 13,
         "cAgeReason": "LSN",
         "iRuntime": 148,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55535
      },
            {
         "dMovieObj": 1140,
         "cMovieCode": "ONEFL001",
         "cMovieTitle": "One Flew Over the Cuckoo's Nest",
         "iMovieYear": 1975,
         "iAgeRestriction": 16,
         "cAgeReason": "SN",
         "iRuntime": 133,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 56005
      },
            {
         "dMovieObj": 1288,
         "cMovieCode": "ISAWT001",
         "cMovieTitle": "I Saw The Devil",
         "iMovieYear": 2011,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 141,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55460
      },
            {
         "dMovieObj": 1296,
         "cMovieCode": "KILLT001",
         "cMovieTitle": "Kill the Irishman",
         "iMovieYear": 2011,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 106,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55625
      },
            {
         "dMovieObj": 1445,
         "cMovieCode": "RISEO001",
         "cMovieTitle": "Rise of the Guardians",
         "iMovieYear": 2012,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 97,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 56205
      },
            {
         "dMovieObj": 1546,
         "cMovieCode": "MOTHE001",
         "cMovieTitle": "Mother",
         "iMovieYear": 2009,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 128,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55865
      },
            {
         "dMovieObj": 1596,
         "cMovieCode": "BLUEI001",
         "cMovieTitle": "Blue Is the Warmest Color",
         "iMovieYear": 2013,
         "iAgeRestriction": 18,
         "cAgeReason": "NC-17",
         "iRuntime": 179,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54855
      },
            {
         "dMovieObj": 1676,
         "cMovieCode": "BENHU002",
         "cMovieTitle": "Ben-Hur: A Tale of the Christ",
         "iMovieYear": 1925,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 143,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54820
      },
            {
         "dMovieObj": 1853,
         "cMovieCode": "OUTOF001",
         "cMovieTitle": "Out of the Past",
         "iMovieYear": 1947,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 97,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 56025
      },
            {
         "dMovieObj": 1900,
         "cMovieCode": "BACKT001",
         "cMovieTitle": "Back to the Future",
         "iMovieYear": 1985,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 111,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54755
      },
            {
         "dMovieObj": 1937,
         "cMovieCode": "RAIDE001",
         "cMovieTitle": "Raiders of the Lost Ark",
         "iMovieYear": 1981,
         "iAgeRestriction": 10,
         "cAgeReason": "NSLV",
         "iRuntime": 115,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 0
      },
            {
         "dMovieObj": 1963,
         "cMovieCode": "ALLQU001",
         "cMovieTitle": "All Quiet on the Western Front",
         "iMovieYear": 1930,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 140,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54680
      },
            {
         "dMovieObj": 2184,
         "cMovieCode": "ANOTH001",
         "cMovieTitle": "Another Year",
         "iMovieYear": 2010,
         "iAgeRestriction": 13,
         "cAgeReason": "PG-13",
         "iRuntime": 129,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54730
      },
            {
         "dMovieObj": 2202,
         "cMovieCode": "DRMAB001",
         "cMovieTitle": "Dr. Mabuse: The Gambler",
         "iMovieYear": 1922,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 195,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55140
      },
            {
         "dMovieObj": 2263,
         "cMovieCode": "MUTIN001",
         "cMovieTitle": "Mutiny on the Bounty",
         "iMovieYear": 1935,
         "iAgeRestriction": 13,
         "cAgeReason": "NR",
         "iRuntime": 132,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55885
      },
            {
         "dMovieObj": 2297,
         "cMovieCode": "AGUIR001",
         "cMovieTitle": "Aguirre: The Wrath of God",
         "iMovieYear": 1972,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 93,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54660
      },
            {
         "dMovieObj": 2312,
         "cMovieCode": "MONTY002",
         "cMovieTitle": "Monty Python and the Holy Grail",
         "iMovieYear": 1975,
         "iAgeRestriction": 18,
         "cAgeReason": "LS",
         "iRuntime": 91,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 55845
      },
            {
         "dMovieObj": 2379,
         "cMovieCode": "INDIA001",
         "cMovieTitle": "Indiana Jones and the Last Crusade",
         "iMovieYear": 1989,
         "iAgeRestriction": 10,
         "cAgeReason": "LVS",
         "iRuntime": 127,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 55510
      },
            {
         "dMovieObj": 2454,
         "cMovieCode": "CASTL001",
         "cMovieTitle": "Castle in the Sky",
         "iMovieYear": 1986,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 124,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54930
      },
            {
         "dMovieObj": 2541,
         "cMovieCode": "IPMAN002",
         "cMovieTitle": "Ip Man 2: Legend of the Grandmaster",
         "iMovieYear": 2011,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 109,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55550
      },
            {
         "dMovieObj": 2628,
         "cMovieCode": "ETERN001",
         "cMovieTitle": "Eternal Sunshine of the Spotless Mind",
         "iMovieYear": 2004,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 108,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55180
      },
            {
         "dMovieObj": 2709,
         "cMovieCode": "BEAUT001",
         "cMovieTitle": "Beauty and the Beast",
         "iMovieYear": 1947,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 96,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54795
      },
            {
         "dMovieObj": 2715,
         "cMovieCode": "ELITE001",
         "cMovieTitle": "Elite Squad: The Enemy Within",
         "iMovieYear": 2011,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 115,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55165
      },
            {
         "dMovieObj": 2721,
         "cMovieCode": "INTHE003",
         "cMovieTitle": "In the Name of the Father",
         "iMovieYear": 1993,
         "iAgeRestriction": 18,
         "cAgeReason": "V",
         "iRuntime": 133,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 0
      },
            {
         "dMovieObj": 2727,
         "cMovieCode": "LETTH001",
         "cMovieTitle": "Let the Right One In",
         "iMovieYear": 2008,
         "iAgeRestriction": 16,
         "cAgeReason": "R",
         "iRuntime": 115,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55715
      },
            {
         "dMovieObj": 2868,
         "cMovieCode": "BUTCH001",
         "cMovieTitle": "Butch Cassidy and the Sundance Kid",
         "iMovieYear": 1969,
         "iAgeRestriction": 10,
         "cAgeReason": "LNSV",
         "iRuntime": 110,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 54900
      },
            {
         "dMovieObj": 2886,
         "cMovieCode": "CAPTA003",
         "cMovieTitle": "Captain America: The Winter Soldier",
         "iMovieYear": 2014,
         "iAgeRestriction": 13,
         "cAgeReason": "PG-13",
         "iRuntime": 128,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 57464
      },
            {
         "dMovieObj": 2992,
         "cMovieCode": "HARRY002",
         "cMovieTitle": "Harry Potter and the Deathly Hallows: Part 2",
         "iMovieYear": 2011,
         "iAgeRestriction": 16,
         "cAgeReason": "VNL",
         "iRuntime": 130,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55385
      },
            {
         "dMovieObj": 3007,
         "cMovieCode": "PIRAT002",
         "cMovieTitle": "Pirates of the Caribbean: The Curse of the Black Pearl",
         "iMovieYear": 2003,
         "iAgeRestriction": 18,
         "cAgeReason": "LS",
         "iRuntime": 143,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 0
      },
            {
         "dMovieObj": 3019,
         "cMovieCode": "HARRY003",
         "cMovieTitle": "Harry Potter and the Deathly Hallows Part 1",
         "iMovieYear": 2010,
         "iAgeRestriction": 13,
         "cAgeReason": "PG-13",
         "iRuntime": 146,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55380
      },
            {
         "dMovieObj": 3033,
         "cMovieCode": "HELLB001",
         "cMovieTitle": "Hellboy II: The Golden Army",
         "iMovieYear": 2008,
         "iAgeRestriction": 13,
         "cAgeReason": "PG-13",
         "iRuntime": 120,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55400
      },
            {
         "dMovieObj": 3063,
         "cMovieCode": "NAUSI001",
         "cMovieTitle": "Nausicaä of the Valley of the Wind",
         "iMovieYear": 1984,
         "iAgeRestriction": 0,
         "cAgeReason": "",
         "iRuntime": 95,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55915
      },
            {
         "dMovieObj": 3070,
         "cMovieCode": "DRSTR001",
         "cMovieTitle": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
         "iMovieYear": 1964,
         "iAgeRestriction": 16,
         "cAgeReason": "SLVN",
         "iRuntime": 95,
         "cMovieTypeKey": "ds_AcDsmpaMovCls",
         "cMovieTypeLabel": "Classic",
         "dPosterObj": 0
      },
            {
         "dMovieObj": 3093,
         "cMovieCode": "HARRY004",
         "cMovieTitle": "Harry Potter and the Half-Blood Prince",
         "iMovieYear": 2009,
         "iAgeRestriction": 10,
         "cAgeReason": "PG",
         "iRuntime": 153,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 55390
      },
            {
         "dMovieObj": 3102,
         "cMovieCode": "BEAUT002",
         "cMovieTitle": "Beauty and the Beast",
         "iMovieYear": 1991,
         "iAgeRestriction": 18,
         "cAgeReason": "N",
         "iRuntime": 91,
         "cMovieTypeKey": "ds_AcDsmpaMovStd",
         "cMovieTypeLabel": "Standard",
         "dPosterObj": 54800
      }
   ]}
}}